language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=4.0

before_script:
    - bash tests/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - composer install --dev
